project_id = "ncetkhcryoxchkodlzgj"

[functions.test-binance-connection]
verify_jwt = false

[functions.analyze-stock]
verify_jwt = true

[functions.execute-trade]
verify_jwt = false

[functions.auto-trade]
verify_jwt = true

[functions.advanced-trading-bot]
verify_jwt = true

[functions.fetch-news]
verify_jwt = true

[functions.update-positions]
verify_jwt = true

[functions.train-ppo-model]
verify_jwt = true

[functions.train-asset-model]
verify_jwt = true

[functions.fetch-crypto-prices]
verify_jwt = false

[functions.fetch-stock-price]
verify_jwt = false

[functions.fetch-stock-history]
verify_jwt = false

[functions.connect-broker]
verify_jwt = true

[functions.generate-signals]
verify_jwt = false

[functions.health-check]
verify_jwt = false

[functions.execute-signal]
verify_jwt = false

[functions.online-ppo-update]
verify_jwt = false

[functions.promote-model]
verify_jwt = true

[functions.safety-monitor]
verify_jwt = false