project_id = "ncetkhcryoxchkodlzgj"

[functions.advanced-trading-bot]
verify_jwt = true

[functions.fetch-binance-symbols]
verify_jwt = false

[functions.trigger-trading-cycle]
verify_jwt = true

[functions.kpi-refresh]
verify_jwt = false

[functions.monthly-retrain]
verify_jwt = false

[functions.admin-dashboard]
verify_jwt = true

[functions.analyze-stock]
verify_jwt = true

[functions.auto-trade]
verify_jwt = true

[functions.connect-broker]
verify_jwt = false

[functions.dashboard]
verify_jwt = true

[functions.execute-signal]
verify_jwt = false

[functions.execute-trade]
verify_jwt = false

[functions.fetch-crypto-prices]
verify_jwt = false

[functions.fetch-news]
verify_jwt = true

[functions.fetch-stock-history]
verify_jwt = false

[functions.fetch-stock-price]
verify_jwt = false

[functions.generate-signals]
verify_jwt = false

[functions.health-check]
verify_jwt = false

[functions.inference-service]
verify_jwt = false

[functions.live-trading-orchestrator]
verify_jwt = false

[functions.online-ppo-update]
verify_jwt = false

[functions.promote-model]
verify_jwt = true

[functions.request-asset-training]
verify_jwt = true

[functions.safety-monitor]
verify_jwt = false

[functions.test-binance-connection]
verify_jwt = false

[functions.train-asset-model]
verify_jwt = false

[functions.train-ppo-model]
verify_jwt = true

[functions.train-recurrent-ppo]
verify_jwt = true

[functions.update-asset-prefs]
verify_jwt = true

[functions.update-positions]
verify_jwt = true

[functions.fetch-binance-portfolio]
verify_jwt = true

[functions.batch-train-cryptos]
verify_jwt = true

[functions.batch-train-assets]
verify_jwt = true

[functions.batch-training-admin]
verify_jwt = true

[functions.process-training-queue]
verify_jwt = false

[functions.batch-training-admin]
verify_jwt = true

[functions.validate-model]
verify_jwt = false

[functions.paper-trade]
verify_jwt = false

[functions.monitor-live-trading]
verify_jwt = false