project_id = "ncetkhcryoxchkodlzgj"

[functions.test-binance-connection]
verify_jwt = false

[functions.analyze-stock]
verify_jwt = true

[functions.execute-trade]
verify_jwt = true

[functions.auto-trade]
verify_jwt = true

[functions.advanced-trading-bot]
verify_jwt = true

[functions.fetch-news]
verify_jwt = true

[functions.update-positions]
verify_jwt = true

[functions.train-ppo-model]
verify_jwt = true

[functions.train-asset-model]
verify_jwt = true

[functions.fetch-crypto-prices]
verify_jwt = false

[functions.fetch-stock-price]
verify_jwt = false

[functions.fetch-stock-history]
verify_jwt = false